spring:
  kafka:
    producer:
      acks: -1
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

telegram:
  bot:
    token: 6190207669:AAGH4fpAanUPKJ-pMwFyPzzL7RfDylSwqW8
    username: suir_registration_bot

server:
  port: 8080
